[package]
name = "serde-arma"
version = "0.1.0"
authors = ["Brett <brett@bmandesigns.com>"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.3"

[dev-dependencies]
serde_json = "*"
serde-transcode = "*"
